redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/home/ubuntu/AnjosUrbanos/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"

[build.environment]
NODE_VERSION = "22"
VITE_GEMINI_API_KEY = "AIzaSyA5KHoNHkfHuRINJY3q6tZa9Uk5sc-MU4s"
VITE_RECORD_TOKEN = "eb4e33d15598ec1c83e5398099b61d717a8c51a3f0d9d7cd578628c89c82954a"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]