[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  VITE_GEMINI_API_KEY = "AIzaSyA5KHoNHkfHuRINJY3q6tZa9Uk5sc-MU4s"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
