[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  VITE_GEMINI_API_KEY = "AIzaSyA0jst4LeuUsJMYDozXyVuHgLf2qTD6paw"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
